// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

@file:Suppress("NAME_SHADOWING")

package uniffi.aetr_core

// Common helper code.
//
// Ideally this would live in a separate .kt file where it can be unittested etc
// in isolation, and perhaps even published as a re-useable package.
//
// However, it's important that the details of how this helper code works (e.g. the
// way that different builtin types are passed across the FFI) exactly match what's
// expected by the Rust code on the other side of the interface. In practice right
// now that means coming from the exact some version of `uniffi` that was used to
// compile the Rust component. The easiest way to ensure this is to bundle the Kotlin
// helpers directly inline like we're doing here.

import com.sun.jna.Library
import com.sun.jna.IntegerType
import com.sun.jna.Native
import com.sun.jna.Pointer
import com.sun.jna.Structure
import com.sun.jna.Callback
import com.sun.jna.ptr.*
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.nio.CharBuffer
import java.nio.charset.CodingErrorAction
import java.util.concurrent.atomic.AtomicLong
import java.util.concurrent.ConcurrentHashMap
import java.util.concurrent.atomic.AtomicBoolean

// This is a helper for safely working with byte buffers returned from the Rust code.
// A rust-owned buffer is represented by its capacity, its current length, and a
// pointer to the underlying data.

/**
 * @suppress
 */
@Structure.FieldOrder("capacity", "len", "data")
open class RustBuffer : Structure() {
    // Note: `capacity` and `len` are actually `ULong` values, but JVM only supports signed values.
    // When dealing with these fields, make sure to call `toULong()`.
    @JvmField var capacity: Long = 0
    @JvmField var len: Long = 0
    @JvmField var data: Pointer? = null

    class ByValue: RustBuffer(), Structure.ByValue
    class ByReference: RustBuffer(), Structure.ByReference

   internal fun setValue(other: RustBuffer) {
        capacity = other.capacity
        len = other.len
        data = other.data
    }

    companion object {
        internal fun alloc(size: ULong = 0UL) = uniffiRustCall() { status ->
            // Note: need to convert the size to a `Long` value to make this work with JVM.
            UniffiLib.INSTANCE.ffi_aetr_core_rustbuffer_alloc(size.toLong(), status)
        }.also {
            if(it.data == null) {
               throw RuntimeException("RustBuffer.alloc() returned null data pointer (size=${size})")
           }
        }

        internal fun create(capacity: ULong, len: ULong, data: Pointer?): RustBuffer.ByValue {
            var buf = RustBuffer.ByValue()
            buf.capacity = capacity.toLong()
            buf.len = len.toLong()
            buf.data = data
            return buf
        }

        internal fun free(buf: RustBuffer.ByValue) = uniffiRustCall() { status ->
            UniffiLib.INSTANCE.ffi_aetr_core_rustbuffer_free(buf, status)
        }
    }

    @Suppress("TooGenericExceptionThrown")
    fun asByteBuffer() =
        this.data?.getByteBuffer(0, this.len.toLong())?.also {
            it.order(ByteOrder.BIG_ENDIAN)
        }
}

/**
 * The equivalent of the `*mut RustBuffer` type.
 * Required for callbacks taking in an out pointer.
 *
 * Size is the sum of all values in the struct.
 *
 * @suppress
 */
class RustBufferByReference : ByReference(16) {
    /**
     * Set the pointed-to `RustBuffer` to the given value.
     */
    fun setValue(value: RustBuffer.ByValue) {
        // NOTE: The offsets are as they are in the C-like struct.
        val pointer = getPointer()
        pointer.setLong(0, value.capacity)
        pointer.setLong(8, value.len)
        pointer.setPointer(16, value.data)
    }

    /**
     * Get a `RustBuffer.ByValue` from this reference.
     */
    fun getValue(): RustBuffer.ByValue {
        val pointer = getPointer()
        val value = RustBuffer.ByValue()
        value.writeField("capacity", pointer.getLong(0))
        value.writeField("len", pointer.getLong(8))
        value.writeField("data", pointer.getLong(16))

        return value
    }
}

// This is a helper for safely passing byte references into the rust code.
// It's not actually used at the moment, because there aren't many things that you
// can take a direct pointer to in the JVM, and if we're going to copy something
// then we might as well copy it into a `RustBuffer`. But it's here for API
// completeness.

@Structure.FieldOrder("len", "data")
internal open class ForeignBytes : Structure() {
    @JvmField var len: Int = 0
    @JvmField var data: Pointer? = null

    class ByValue : ForeignBytes(), Structure.ByValue
}
/**
 * The FfiConverter interface handles converter types to and from the FFI
 *
 * All implementing objects should be public to support external types.  When a
 * type is external we need to import it's FfiConverter.
 *
 * @suppress
 */
public interface FfiConverter<KotlinType, FfiType> {
    // Convert an FFI type to a Kotlin type
    fun lift(value: FfiType): KotlinType

    // Convert an Kotlin type to an FFI type
    fun lower(value: KotlinType): FfiType

    // Read a Kotlin type from a `ByteBuffer`
    fun read(buf: ByteBuffer): KotlinType

    // Calculate bytes to allocate when creating a `RustBuffer`
    //
    // This must return at least as many bytes as the write() function will
    // write. It can return more bytes than needed, for example when writing
    // Strings we can't know the exact bytes needed until we the UTF-8
    // encoding, so we pessimistically allocate the largest size possible (3
    // bytes per codepoint).  Allocating extra bytes is not really a big deal
    // because the `RustBuffer` is short-lived.
    fun allocationSize(value: KotlinType): ULong

    // Write a Kotlin type to a `ByteBuffer`
    fun write(value: KotlinType, buf: ByteBuffer)

    // Lower a value into a `RustBuffer`
    //
    // This method lowers a value into a `RustBuffer` rather than the normal
    // FfiType.  It's used by the callback interface code.  Callback interface
    // returns are always serialized into a `RustBuffer` regardless of their
    // normal FFI type.
    fun lowerIntoRustBuffer(value: KotlinType): RustBuffer.ByValue {
        val rbuf = RustBuffer.alloc(allocationSize(value))
        try {
            val bbuf = rbuf.data!!.getByteBuffer(0, rbuf.capacity).also {
                it.order(ByteOrder.BIG_ENDIAN)
            }
            write(value, bbuf)
            rbuf.writeField("len", bbuf.position().toLong())
            return rbuf
        } catch (e: Throwable) {
            RustBuffer.free(rbuf)
            throw e
        }
    }

    // Lift a value from a `RustBuffer`.
    //
    // This here mostly because of the symmetry with `lowerIntoRustBuffer()`.
    // It's currently only used by the `FfiConverterRustBuffer` class below.
    fun liftFromRustBuffer(rbuf: RustBuffer.ByValue): KotlinType {
        val byteBuf = rbuf.asByteBuffer()!!
        try {
           val item = read(byteBuf)
           if (byteBuf.hasRemaining()) {
               throw RuntimeException("junk remaining in buffer after lifting, something is very wrong!!")
           }
           return item
        } finally {
            RustBuffer.free(rbuf)
        }
    }
}

/**
 * FfiConverter that uses `RustBuffer` as the FfiType
 *
 * @suppress
 */
public interface FfiConverterRustBuffer<KotlinType>: FfiConverter<KotlinType, RustBuffer.ByValue> {
    override fun lift(value: RustBuffer.ByValue) = liftFromRustBuffer(value)
    override fun lower(value: KotlinType) = lowerIntoRustBuffer(value)
}
// A handful of classes and functions to support the generated data structures.
// This would be a good candidate for isolating in its own ffi-support lib.

internal const val UNIFFI_CALL_SUCCESS = 0.toByte()
internal const val UNIFFI_CALL_ERROR = 1.toByte()
internal const val UNIFFI_CALL_UNEXPECTED_ERROR = 2.toByte()

@Structure.FieldOrder("code", "error_buf")
internal open class UniffiRustCallStatus : Structure() {
    @JvmField var code: Byte = 0
    @JvmField var error_buf: RustBuffer.ByValue = RustBuffer.ByValue()

    class ByValue: UniffiRustCallStatus(), Structure.ByValue

    fun isSuccess(): Boolean {
        return code == UNIFFI_CALL_SUCCESS
    }

    fun isError(): Boolean {
        return code == UNIFFI_CALL_ERROR
    }

    fun isPanic(): Boolean {
        return code == UNIFFI_CALL_UNEXPECTED_ERROR
    }

    companion object {
        fun create(code: Byte, errorBuf: RustBuffer.ByValue): UniffiRustCallStatus.ByValue {
            val callStatus = UniffiRustCallStatus.ByValue()
            callStatus.code = code
            callStatus.error_buf = errorBuf
            return callStatus
        }
    }
}

class InternalException(message: String) : kotlin.Exception(message)

/**
 * Each top-level error class has a companion object that can lift the error from the call status's rust buffer
 *
 * @suppress
 */
interface UniffiRustCallStatusErrorHandler<E> {
    fun lift(error_buf: RustBuffer.ByValue): E;
}

// Helpers for calling Rust
// In practice we usually need to be synchronized to call this safely, so it doesn't
// synchronize itself

// Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
private inline fun <U, E: kotlin.Exception> uniffiRustCallWithError(errorHandler: UniffiRustCallStatusErrorHandler<E>, callback: (UniffiRustCallStatus) -> U): U {
    var status = UniffiRustCallStatus()
    val return_value = callback(status)
    uniffiCheckCallStatus(errorHandler, status)
    return return_value
}

// Check UniffiRustCallStatus and throw an error if the call wasn't successful
private fun<E: kotlin.Exception> uniffiCheckCallStatus(errorHandler: UniffiRustCallStatusErrorHandler<E>, status: UniffiRustCallStatus) {
    if (status.isSuccess()) {
        return
    } else if (status.isError()) {
        throw errorHandler.lift(status.error_buf)
    } else if (status.isPanic()) {
        // when the rust code sees a panic, it tries to construct a rustbuffer
        // with the message.  but if that code panics, then it just sends back
        // an empty buffer.
        if (status.error_buf.len > 0) {
            throw InternalException(FfiConverterString.lift(status.error_buf))
        } else {
            throw InternalException("Rust panic")
        }
    } else {
        throw InternalException("Unknown rust call status: $status.code")
    }
}

/**
 * UniffiRustCallStatusErrorHandler implementation for times when we don't expect a CALL_ERROR
 *
 * @suppress
 */
object UniffiNullRustCallStatusErrorHandler: UniffiRustCallStatusErrorHandler<InternalException> {
    override fun lift(error_buf: RustBuffer.ByValue): InternalException {
        RustBuffer.free(error_buf)
        return InternalException("Unexpected CALL_ERROR")
    }
}

// Call a rust function that returns a plain value
private inline fun <U> uniffiRustCall(callback: (UniffiRustCallStatus) -> U): U {
    return uniffiRustCallWithError(UniffiNullRustCallStatusErrorHandler, callback)
}

internal inline fun<T> uniffiTraitInterfaceCall(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
        callStatus.error_buf = FfiConverterString.lower(e.toString())
    }
}

internal inline fun<T, reified E: Throwable> uniffiTraitInterfaceCallWithError(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
    lowerError: (E) -> RustBuffer.ByValue
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        if (e is E) {
            callStatus.code = UNIFFI_CALL_ERROR
            callStatus.error_buf = lowerError(e)
        } else {
            callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
            callStatus.error_buf = FfiConverterString.lower(e.toString())
        }
    }
}
// Map handles to objects
//
// This is used pass an opaque 64-bit handle representing a foreign object to the Rust code.
internal class UniffiHandleMap<T: Any> {
    private val map = ConcurrentHashMap<Long, T>()
    private val counter = java.util.concurrent.atomic.AtomicLong(0)

    val size: Int
        get() = map.size

    // Insert a new object into the handle map and get a handle for it
    fun insert(obj: T): Long {
        val handle = counter.getAndAdd(1)
        map.put(handle, obj)
        return handle
    }

    // Get an object from the handle map
    fun get(handle: Long): T {
        return map.get(handle) ?: throw InternalException("UniffiHandleMap.get: Invalid handle")
    }

    // Remove an entry from the handlemap and get the Kotlin object back
    fun remove(handle: Long): T {
        return map.remove(handle) ?: throw InternalException("UniffiHandleMap: Invalid handle")
    }
}

// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.
@Synchronized
private fun findLibraryName(componentName: String): String {
    val libOverride = System.getProperty("uniffi.component.$componentName.libraryOverride")
    if (libOverride != null) {
        return libOverride
    }
    return "aetr_core"
}

private inline fun <reified Lib : Library> loadIndirect(
    componentName: String
): Lib {
    return Native.load<Lib>(findLibraryName(componentName), Lib::class.java)
}

// Define FFI callback types
internal interface UniffiRustFutureContinuationCallback : com.sun.jna.Callback {
    fun callback(`data`: Long,`pollResult`: Byte,)
}
internal interface UniffiForeignFutureFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
internal interface UniffiCallbackInterfaceFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
@Structure.FieldOrder("handle", "free")
internal open class UniffiForeignFuture(
    @JvmField internal var `handle`: Long = 0.toLong(),
    @JvmField internal var `free`: UniffiForeignFutureFree? = null,
) : Structure() {
    class UniffiByValue(
        `handle`: Long = 0.toLong(),
        `free`: UniffiForeignFutureFree? = null,
    ): UniffiForeignFuture(`handle`,`free`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFuture) {
        `handle` = other.`handle`
        `free` = other.`free`
    }

}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructF32(
    @JvmField internal var `returnValue`: Float = 0.0f,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Float = 0.0f,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructF32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructF32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructF32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructF64(
    @JvmField internal var `returnValue`: Double = 0.0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Double = 0.0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructF64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructF64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructF64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructPointer(
    @JvmField internal var `returnValue`: Pointer = Pointer.NULL,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Pointer = Pointer.NULL,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructPointer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructPointer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompletePointer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructPointer.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructRustBuffer(
    @JvmField internal var `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructRustBuffer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructRustBuffer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteRustBuffer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructRustBuffer.UniffiByValue,)
}
@Structure.FieldOrder("callStatus")
internal open class UniffiForeignFutureStructVoid(
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructVoid(`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructVoid) {
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteVoid : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructVoid.UniffiByValue,)
}


















































































// For large crates we prevent `MethodTooLargeException` (see #2340)
// N.B. the name of the extension is very misleading, since it is 
// rather `InterfaceTooLargeException`, caused by too many methods 
// in the interface for large crates.
//
// By splitting the otherwise huge interface into two parts
// * UniffiLib 
// * IntegrityCheckingUniffiLib (this)
// we allow for ~2x as many methods in the UniffiLib interface.
// 
// The `ffi_uniffi_contract_version` method and all checksum methods are put 
// into `IntegrityCheckingUniffiLib` and these methods are called only once,
// when the library is loaded.
internal interface IntegrityCheckingUniffiLib : Library {
    // Integrity check functions only
    fun uniffi_aetr_core_checksum_func_estimate_airtime_secs(
): Short
fun uniffi_aetr_core_checksum_method_aetrsession_encode_text(
): Short
fun uniffi_aetr_core_checksum_method_aetrsession_encode_voice(
): Short
fun uniffi_aetr_core_checksum_method_aetrsession_poll_events(
): Short
fun uniffi_aetr_core_checksum_method_aetrsession_push_rx(
): Short
fun uniffi_aetr_core_checksum_method_aetrsession_request_repair(
): Short
fun uniffi_aetr_core_checksum_method_aetrsession_reset_rx(
): Short
fun uniffi_aetr_core_checksum_method_aetrsession_rx_state(
): Short
fun uniffi_aetr_core_checksum_method_aetrsession_tx_delay_ms(
): Short
fun uniffi_aetr_core_checksum_method_aetrsession_voice_cap_secs(
): Short
fun uniffi_aetr_core_checksum_constructor_aetrsession_new(
): Short
fun ffi_aetr_core_uniffi_contract_version(
): Int

}

// A JNA Library to expose the extern-C FFI definitions.
// This is an implementation detail which will be called internally by the public API.
internal interface UniffiLib : Library {
    companion object {
        internal val INSTANCE: UniffiLib by lazy {
            val componentName = "aetr_core"
            // For large crates we prevent `MethodTooLargeException` (see #2340)
            // N.B. the name of the extension is very misleading, since it is 
            // rather `InterfaceTooLargeException`, caused by too many methods 
            // in the interface for large crates.
            //
            // By splitting the otherwise huge interface into two parts
            // * UniffiLib (this)
            // * IntegrityCheckingUniffiLib
            // And all checksum methods are put into `IntegrityCheckingUniffiLib`
            // we allow for ~2x as many methods in the UniffiLib interface.
            // 
            // Thus we first load the library with `loadIndirect` as `IntegrityCheckingUniffiLib`
            // so that we can (optionally!) call `uniffiCheckApiChecksums`...
            loadIndirect<IntegrityCheckingUniffiLib>(componentName)
                .also { lib: IntegrityCheckingUniffiLib ->
                    uniffiCheckContractApiVersion(lib)
                    uniffiCheckApiChecksums(lib)
                }
            // ... and then we load the library as `UniffiLib`
            // N.B. we cannot use `loadIndirect` once and then try to cast it to `UniffiLib`
            // => results in `java.lang.ClassCastException: com.sun.proxy.$Proxy cannot be cast to ...`
            // error. So we must call `loadIndirect` twice. For crates large enough
            // to trigger this issue, the performance impact is negligible, running on
            // a macOS M1 machine the `loadIndirect` call takes ~50ms.
            val lib = loadIndirect<UniffiLib>(componentName)
            // No need to check the contract version and checksums, since 
            // we already did that with `IntegrityCheckingUniffiLib` above.
            // Loading of library with integrity check done.
            lib
        }
        
        // The Cleaner for the whole library
        internal val CLEANER: UniffiCleaner by lazy {
            UniffiCleaner.create()
        }
    }

    // FFI functions
    fun uniffi_aetr_core_fn_clone_aetrsession(`ptr`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
): Pointer
fun uniffi_aetr_core_fn_free_aetrsession(`ptr`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
): Unit
fun uniffi_aetr_core_fn_constructor_aetrsession_new(`config`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): Pointer
fun uniffi_aetr_core_fn_method_aetrsession_encode_text(`ptr`: Pointer,`text`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_aetr_core_fn_method_aetrsession_encode_voice(`ptr`: Pointer,`pcm48k`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_aetr_core_fn_method_aetrsession_poll_events(`ptr`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_aetr_core_fn_method_aetrsession_push_rx(`ptr`: Pointer,`pcm48k`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): Unit
fun uniffi_aetr_core_fn_method_aetrsession_request_repair(`ptr`: Pointer,`messageId`: Long,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_aetr_core_fn_method_aetrsession_reset_rx(`ptr`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
): Unit
fun uniffi_aetr_core_fn_method_aetrsession_rx_state(`ptr`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_aetr_core_fn_method_aetrsession_tx_delay_ms(`ptr`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
): Int
fun uniffi_aetr_core_fn_method_aetrsession_voice_cap_secs(`ptr`: Pointer,uniffi_out_err: UniffiRustCallStatus, 
): Int
fun uniffi_aetr_core_fn_func_estimate_airtime_secs(`mode`: RustBuffer.ByValue,`kind`: RustBuffer.ByValue,`len`: Long,`txDelayMs`: Int,uniffi_out_err: UniffiRustCallStatus, 
): Double
fun ffi_aetr_core_rustbuffer_alloc(`size`: Long,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun ffi_aetr_core_rustbuffer_from_bytes(`bytes`: ForeignBytes.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun ffi_aetr_core_rustbuffer_free(`buf`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): Unit
fun ffi_aetr_core_rustbuffer_reserve(`buf`: RustBuffer.ByValue,`additional`: Long,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun ffi_aetr_core_rust_future_poll_u8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_aetr_core_rust_future_cancel_u8(`handle`: Long,
): Unit
fun ffi_aetr_core_rust_future_free_u8(`handle`: Long,
): Unit
fun ffi_aetr_core_rust_future_complete_u8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Byte
fun ffi_aetr_core_rust_future_poll_i8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_aetr_core_rust_future_cancel_i8(`handle`: Long,
): Unit
fun ffi_aetr_core_rust_future_free_i8(`handle`: Long,
): Unit
fun ffi_aetr_core_rust_future_complete_i8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Byte
fun ffi_aetr_core_rust_future_poll_u16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_aetr_core_rust_future_cancel_u16(`handle`: Long,
): Unit
fun ffi_aetr_core_rust_future_free_u16(`handle`: Long,
): Unit
fun ffi_aetr_core_rust_future_complete_u16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Short
fun ffi_aetr_core_rust_future_poll_i16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_aetr_core_rust_future_cancel_i16(`handle`: Long,
): Unit
fun ffi_aetr_core_rust_future_free_i16(`handle`: Long,
): Unit
fun ffi_aetr_core_rust_future_complete_i16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Short
fun ffi_aetr_core_rust_future_poll_u32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_aetr_core_rust_future_cancel_u32(`handle`: Long,
): Unit
fun ffi_aetr_core_rust_future_free_u32(`handle`: Long,
): Unit
fun ffi_aetr_core_rust_future_complete_u32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Int
fun ffi_aetr_core_rust_future_poll_i32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_aetr_core_rust_future_cancel_i32(`handle`: Long,
): Unit
fun ffi_aetr_core_rust_future_free_i32(`handle`: Long,
): Unit
fun ffi_aetr_core_rust_future_complete_i32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Int
fun ffi_aetr_core_rust_future_poll_u64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_aetr_core_rust_future_cancel_u64(`handle`: Long,
): Unit
fun ffi_aetr_core_rust_future_free_u64(`handle`: Long,
): Unit
fun ffi_aetr_core_rust_future_complete_u64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Long
fun ffi_aetr_core_rust_future_poll_i64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_aetr_core_rust_future_cancel_i64(`handle`: Long,
): Unit
fun ffi_aetr_core_rust_future_free_i64(`handle`: Long,
): Unit
fun ffi_aetr_core_rust_future_complete_i64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Long
fun ffi_aetr_core_rust_future_poll_f32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_aetr_core_rust_future_cancel_f32(`handle`: Long,
): Unit
fun ffi_aetr_core_rust_future_free_f32(`handle`: Long,
): Unit
fun ffi_aetr_core_rust_future_complete_f32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Float
fun ffi_aetr_core_rust_future_poll_f64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_aetr_core_rust_future_cancel_f64(`handle`: Long,
): Unit
fun ffi_aetr_core_rust_future_free_f64(`handle`: Long,
): Unit
fun ffi_aetr_core_rust_future_complete_f64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Double
fun ffi_aetr_core_rust_future_poll_pointer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_aetr_core_rust_future_cancel_pointer(`handle`: Long,
): Unit
fun ffi_aetr_core_rust_future_free_pointer(`handle`: Long,
): Unit
fun ffi_aetr_core_rust_future_complete_pointer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Pointer
fun ffi_aetr_core_rust_future_poll_rust_buffer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_aetr_core_rust_future_cancel_rust_buffer(`handle`: Long,
): Unit
fun ffi_aetr_core_rust_future_free_rust_buffer(`handle`: Long,
): Unit
fun ffi_aetr_core_rust_future_complete_rust_buffer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun ffi_aetr_core_rust_future_poll_void(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_aetr_core_rust_future_cancel_void(`handle`: Long,
): Unit
fun ffi_aetr_core_rust_future_free_void(`handle`: Long,
): Unit
fun ffi_aetr_core_rust_future_complete_void(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Unit

}

private fun uniffiCheckContractApiVersion(lib: IntegrityCheckingUniffiLib) {
    // Get the bindings contract version from our ComponentInterface
    val bindings_contract_version = 29
    // Get the scaffolding contract version by calling the into the dylib
    val scaffolding_contract_version = lib.ffi_aetr_core_uniffi_contract_version()
    if (bindings_contract_version != scaffolding_contract_version) {
        throw RuntimeException("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    }
}
@Suppress("UNUSED_PARAMETER")
private fun uniffiCheckApiChecksums(lib: IntegrityCheckingUniffiLib) {
    if (lib.uniffi_aetr_core_checksum_func_estimate_airtime_secs() != 21146.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_aetr_core_checksum_method_aetrsession_encode_text() != 29.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_aetr_core_checksum_method_aetrsession_encode_voice() != 43857.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_aetr_core_checksum_method_aetrsession_poll_events() != 32554.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_aetr_core_checksum_method_aetrsession_push_rx() != 10023.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_aetr_core_checksum_method_aetrsession_request_repair() != 23051.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_aetr_core_checksum_method_aetrsession_reset_rx() != 22385.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_aetr_core_checksum_method_aetrsession_rx_state() != 35385.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_aetr_core_checksum_method_aetrsession_tx_delay_ms() != 29899.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_aetr_core_checksum_method_aetrsession_voice_cap_secs() != 13488.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_aetr_core_checksum_constructor_aetrsession_new() != 43924.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

/**
 * @suppress
 */
public fun uniffiEnsureInitialized() {
    UniffiLib.INSTANCE
}

// Async support

// Public interface members begin here.


// Interface implemented by anything that can contain an object reference.
//
// Such types expose a `destroy()` method that must be called to cleanly
// dispose of the contained objects. Failure to call this method may result
// in memory leaks.
//
// The easiest way to ensure this method is called is to use the `.use`
// helper method to execute a block and destroy the object at the end.
interface Disposable {
    fun destroy()
    companion object {
        fun destroy(vararg args: Any?) {
            for (arg in args) {
                when (arg) {
                    is Disposable -> arg.destroy()
                    is ArrayList<*> -> {
                        for (idx in arg.indices) {
                            val element = arg[idx]
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                    is Map<*, *> -> {
                        for (element in arg.values) {
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                    is Iterable<*> -> {
                        for (element in arg) {
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                }
            }
        }
    }
}

/**
 * @suppress
 */
inline fun <T : Disposable?, R> T.use(block: (T) -> R) =
    try {
        block(this)
    } finally {
        try {
            // N.B. our implementation is on the nullable type `Disposable?`.
            this?.destroy()
        } catch (e: Throwable) {
            // swallow
        }
    }

/** 
 * Used to instantiate an interface without an actual pointer, for fakes in tests, mostly.
 *
 * @suppress
 * */
object NoPointer
/**
 * The cleaner interface for Object finalization code to run.
 * This is the entry point to any implementation that we're using.
 *
 * The cleaner registers objects and returns cleanables, so now we are
 * defining a `UniffiCleaner` with a `UniffiClenaer.Cleanable` to abstract the
 * different implmentations available at compile time.
 *
 * @suppress
 */
interface UniffiCleaner {
    interface Cleanable {
        fun clean()
    }

    fun register(value: Any, cleanUpTask: Runnable): UniffiCleaner.Cleanable

    companion object
}

// The fallback Jna cleaner, which is available for both Android, and the JVM.
private class UniffiJnaCleaner : UniffiCleaner {
    private val cleaner = com.sun.jna.internal.Cleaner.getCleaner()

    override fun register(value: Any, cleanUpTask: Runnable): UniffiCleaner.Cleanable =
        UniffiJnaCleanable(cleaner.register(value, cleanUpTask))
}

private class UniffiJnaCleanable(
    private val cleanable: com.sun.jna.internal.Cleaner.Cleanable,
) : UniffiCleaner.Cleanable {
    override fun clean() = cleanable.clean()
}


// We decide at uniffi binding generation time whether we were
// using Android or not.
// There are further runtime checks to chose the correct implementation
// of the cleaner.
private fun UniffiCleaner.Companion.create(): UniffiCleaner =
    try {
        // For safety's sake: if the library hasn't been run in android_cleaner = true
        // mode, but is being run on Android, then we still need to think about
        // Android API versions.
        // So we check if java.lang.ref.Cleaner is there, and use that…
        java.lang.Class.forName("java.lang.ref.Cleaner")
        JavaLangRefCleaner()
    } catch (e: ClassNotFoundException) {
        // … otherwise, fallback to the JNA cleaner.
        UniffiJnaCleaner()
    }

private class JavaLangRefCleaner : UniffiCleaner {
    val cleaner = java.lang.ref.Cleaner.create()

    override fun register(value: Any, cleanUpTask: Runnable): UniffiCleaner.Cleanable =
        JavaLangRefCleanable(cleaner.register(value, cleanUpTask))
}

private class JavaLangRefCleanable(
    val cleanable: java.lang.ref.Cleaner.Cleanable
) : UniffiCleaner.Cleanable {
    override fun clean() = cleanable.clean()
}

/**
 * @suppress
 */
public object FfiConverterUInt: FfiConverter<UInt, Int> {
    override fun lift(value: Int): UInt {
        return value.toUInt()
    }

    override fun read(buf: ByteBuffer): UInt {
        return lift(buf.getInt())
    }

    override fun lower(value: UInt): Int {
        return value.toInt()
    }

    override fun allocationSize(value: UInt) = 4UL

    override fun write(value: UInt, buf: ByteBuffer) {
        buf.putInt(value.toInt())
    }
}

/**
 * @suppress
 */
public object FfiConverterULong: FfiConverter<ULong, Long> {
    override fun lift(value: Long): ULong {
        return value.toULong()
    }

    override fun read(buf: ByteBuffer): ULong {
        return lift(buf.getLong())
    }

    override fun lower(value: ULong): Long {
        return value.toLong()
    }

    override fun allocationSize(value: ULong) = 8UL

    override fun write(value: ULong, buf: ByteBuffer) {
        buf.putLong(value.toLong())
    }
}

/**
 * @suppress
 */
public object FfiConverterFloat: FfiConverter<Float, Float> {
    override fun lift(value: Float): Float {
        return value
    }

    override fun read(buf: ByteBuffer): Float {
        return buf.getFloat()
    }

    override fun lower(value: Float): Float {
        return value
    }

    override fun allocationSize(value: Float) = 4UL

    override fun write(value: Float, buf: ByteBuffer) {
        buf.putFloat(value)
    }
}

/**
 * @suppress
 */
public object FfiConverterDouble: FfiConverter<Double, Double> {
    override fun lift(value: Double): Double {
        return value
    }

    override fun read(buf: ByteBuffer): Double {
        return buf.getDouble()
    }

    override fun lower(value: Double): Double {
        return value
    }

    override fun allocationSize(value: Double) = 8UL

    override fun write(value: Double, buf: ByteBuffer) {
        buf.putDouble(value)
    }
}

/**
 * @suppress
 */
public object FfiConverterBoolean: FfiConverter<Boolean, Byte> {
    override fun lift(value: Byte): Boolean {
        return value.toInt() != 0
    }

    override fun read(buf: ByteBuffer): Boolean {
        return lift(buf.get())
    }

    override fun lower(value: Boolean): Byte {
        return if (value) 1.toByte() else 0.toByte()
    }

    override fun allocationSize(value: Boolean) = 1UL

    override fun write(value: Boolean, buf: ByteBuffer) {
        buf.put(lower(value))
    }
}

/**
 * @suppress
 */
public object FfiConverterString: FfiConverter<String, RustBuffer.ByValue> {
    // Note: we don't inherit from FfiConverterRustBuffer, because we use a
    // special encoding when lowering/lifting.  We can use `RustBuffer.len` to
    // store our length and avoid writing it out to the buffer.
    override fun lift(value: RustBuffer.ByValue): String {
        try {
            val byteArr = ByteArray(value.len.toInt())
            value.asByteBuffer()!!.get(byteArr)
            return byteArr.toString(Charsets.UTF_8)
        } finally {
            RustBuffer.free(value)
        }
    }

    override fun read(buf: ByteBuffer): String {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr.toString(Charsets.UTF_8)
    }

    fun toUtf8(value: String): ByteBuffer {
        // Make sure we don't have invalid UTF-16, check for lone surrogates.
        return Charsets.UTF_8.newEncoder().run {
            onMalformedInput(CodingErrorAction.REPORT)
            encode(CharBuffer.wrap(value))
        }
    }

    override fun lower(value: String): RustBuffer.ByValue {
        val byteBuf = toUtf8(value)
        // Ideally we'd pass these bytes to `ffi_bytebuffer_from_bytes`, but doing so would require us
        // to copy them into a JNA `Memory`. So we might as well directly copy them into a `RustBuffer`.
        val rbuf = RustBuffer.alloc(byteBuf.limit().toULong())
        rbuf.asByteBuffer()!!.put(byteBuf)
        return rbuf
    }

    // We aren't sure exactly how many bytes our string will be once it's UTF-8
    // encoded.  Allocate 3 bytes per UTF-16 code unit which will always be
    // enough.
    override fun allocationSize(value: String): ULong {
        val sizeForLength = 4UL
        val sizeForString = value.length.toULong() * 3UL
        return sizeForLength + sizeForString
    }

    override fun write(value: String, buf: ByteBuffer) {
        val byteBuf = toUtf8(value)
        buf.putInt(byteBuf.limit())
        buf.put(byteBuf)
    }
}


// This template implements a class for working with a Rust struct via a Pointer/Arc<T>
// to the live Rust struct on the other side of the FFI.
//
// Each instance implements core operations for working with the Rust `Arc<T>` and the
// Kotlin Pointer to work with the live Rust struct on the other side of the FFI.
//
// There's some subtlety here, because we have to be careful not to operate on a Rust
// struct after it has been dropped, and because we must expose a public API for freeing
// theq Kotlin wrapper object in lieu of reliable finalizers. The core requirements are:
//
//   * Each instance holds an opaque pointer to the underlying Rust struct.
//     Method calls need to read this pointer from the object's state and pass it in to
//     the Rust FFI.
//
//   * When an instance is no longer needed, its pointer should be passed to a
//     special destructor function provided by the Rust FFI, which will drop the
//     underlying Rust struct.
//
//   * Given an instance, calling code is expected to call the special
//     `destroy` method in order to free it after use, either by calling it explicitly
//     or by using a higher-level helper like the `use` method. Failing to do so risks
//     leaking the underlying Rust struct.
//
//   * We can't assume that calling code will do the right thing, and must be prepared
//     to handle Kotlin method calls executing concurrently with or even after a call to
//     `destroy`, and to handle multiple (possibly concurrent!) calls to `destroy`.
//
//   * We must never allow Rust code to operate on the underlying Rust struct after
//     the destructor has been called, and must never call the destructor more than once.
//     Doing so may trigger memory unsafety.
//
//   * To mitigate many of the risks of leaking memory and use-after-free unsafety, a `Cleaner`
//     is implemented to call the destructor when the Kotlin object becomes unreachable.
//     This is done in a background thread. This is not a panacea, and client code should be aware that
//      1. the thread may starve if some there are objects that have poorly performing
//     `drop` methods or do significant work in their `drop` methods.
//      2. the thread is shared across the whole library. This can be tuned by using `android_cleaner = true`,
//         or `android = true` in the [`kotlin` section of the `uniffi.toml` file](https://mozilla.github.io/uniffi-rs/kotlin/configuration.html).
//
// If we try to implement this with mutual exclusion on access to the pointer, there is the
// possibility of a race between a method call and a concurrent call to `destroy`:
//
//    * Thread A starts a method call, reads the value of the pointer, but is interrupted
//      before it can pass the pointer over the FFI to Rust.
//    * Thread B calls `destroy` and frees the underlying Rust struct.
//    * Thread A resumes, passing the already-read pointer value to Rust and triggering
//      a use-after-free.
//
// One possible solution would be to use a `ReadWriteLock`, with each method call taking
// a read lock (and thus allowed to run concurrently) and the special `destroy` method
// taking a write lock (and thus blocking on live method calls). However, we aim not to
// generate methods with any hidden blocking semantics, and a `destroy` method that might
// block if called incorrectly seems to meet that bar.
//
// So, we achieve our goals by giving each instance an associated `AtomicLong` counter to track
// the number of in-flight method calls, and an `AtomicBoolean` flag to indicate whether `destroy`
// has been called. These are updated according to the following rules:
//
//    * The initial value of the counter is 1, indicating a live object with no in-flight calls.
//      The initial value for the flag is false.
//
//    * At the start of each method call, we atomically check the counter.
//      If it is 0 then the underlying Rust struct has already been destroyed and the call is aborted.
//      If it is nonzero them we atomically increment it by 1 and proceed with the method call.
//
//    * At the end of each method call, we atomically decrement and check the counter.
//      If it has reached zero then we destroy the underlying Rust struct.
//
//    * When `destroy` is called, we atomically flip the flag from false to true.
//      If the flag was already true we silently fail.
//      Otherwise we atomically decrement and check the counter.
//      If it has reached zero then we destroy the underlying Rust struct.
//
// Astute readers may observe that this all sounds very similar to the way that Rust's `Arc<T>` works,
// and indeed it is, with the addition of a flag to guard against multiple calls to `destroy`.
//
// The overall effect is that the underlying Rust struct is destroyed only when `destroy` has been
// called *and* all in-flight method calls have completed, avoiding violating any of the expectations
// of the underlying Rust code.
//
// This makes a cleaner a better alternative to _not_ calling `destroy()` as
// and when the object is finished with, but the abstraction is not perfect: if the Rust object's `drop`
// method is slow, and/or there are many objects to cleanup, and it's on a low end Android device, then the cleaner
// thread may be starved, and the app will leak memory.
//
// In this case, `destroy`ing manually may be a better solution.
//
// The cleaner can live side by side with the manual calling of `destroy`. In the order of responsiveness, uniffi objects
// with Rust peers are reclaimed:
//
// 1. By calling the `destroy` method of the object, which calls `rustObject.free()`. If that doesn't happen:
// 2. When the object becomes unreachable, AND the Cleaner thread gets to call `rustObject.free()`. If the thread is starved then:
// 3. The memory is reclaimed when the process terminates.
//
// [1] https://stackoverflow.com/questions/24376768/can-java-finalize-an-object-when-it-is-still-in-scope/24380219
//


/**
 * One encrypted text/voice session over one audio channel. Construction
 * runs the Argon2id KDF (blocking, ~100 ms); everything after is cheap.
 */
public interface AetrSessionInterface {
    
    /**
     * Encodes a text message into one complete 48 kHz PCM transmission
     * (all bursts, gaps, lead-in/tail) and caches the RS parity pool for a
     * later ARQ round.
     */
    fun `encodeText`(`text`: kotlin.String): List<kotlin.Float>
    
    /**
     * Encodes a 48 kHz mono voice clip into one complete PCM transmission.
     * Rejects clips longer than the configured cap; caches the spans for a
     * later exact-retransmission ARQ round.
     */
    fun `encodeVoice`(`pcm48k`: List<kotlin.Float>): List<kotlin.Float>
    
    /**
     * Drains queued events. Also sweeps the reassembly timeout: stale
     * voice finalizes with silence gaps, stale text becomes `Failed`.
     * Poll at ~10 Hz from the UI.
     */
    fun `pollEvents`(): List<RxEvent>
    
    /**
     * Feeds received PCM (any block size, called from the audio thread).
     * Cheap: buffers into the modem, decrypts any completed frames, and
     * queues events — including automatic `RepairRequested` responses when
     * a peer's control frame targets one of our cached messages. Frames
     * that fail authentication (wrong passphrase on the channel) or are
     * malformed are silently dropped, as on any shared radio channel.
     */
    fun `pushRx`(`pcm48k`: List<kotlin.Float>)
    
    /**
     * Builds the receiver side of the ARQ round: a single control-frame
     * transmission asking the original sender to repair `message_id`.
     * Errors if the message is unknown or already complete. The sender's
     * session answers automatically via `RxEvent::RepairRequested`.
     */
    fun `requestRepair`(`messageId`: kotlin.ULong): List<kotlin.Float>
    
    /**
     * Discards all receive state (in-flight messages, queued events,
     * modem sync). Keeps the key, mode, and sender-side ARQ caches.
     */
    fun `resetRx`()
    
    /**
     * Current receiver state for a UI badge.
     */
    fun `rxState`(): RxState
    
    /**
     * The configured TX key-up delay in milliseconds.
     */
    fun `txDelayMs`(): kotlin.UInt
    
    /**
     * The configured voice clip cap in seconds.
     */
    fun `voiceCapSecs`(): kotlin.UInt
    
    companion object
}

/**
 * One encrypted text/voice session over one audio channel. Construction
 * runs the Argon2id KDF (blocking, ~100 ms); everything after is cheap.
 */
open class AetrSession: Disposable, AutoCloseable, AetrSessionInterface
{

    constructor(pointer: Pointer) {
        this.pointer = pointer
        this.cleanable = UniffiLib.CLEANER.register(this, UniffiCleanAction(pointer))
    }

    /**
     * This constructor can be used to instantiate a fake object. Only used for tests. Any
     * attempt to actually use an object constructed this way will fail as there is no
     * connected Rust object.
     */
    @Suppress("UNUSED_PARAMETER")
    constructor(noPointer: NoPointer) {
        this.pointer = null
        this.cleanable = UniffiLib.CLEANER.register(this, UniffiCleanAction(pointer))
    }
    /**
     * Creates a session: derives the key from the passphrase (blocking
     * Argon2id, ~100 ms — call off the UI thread) and allocates the
     * streaming receiver.
     */
    constructor(`config`: SessionConfig) :
        this(
    uniffiRustCallWithError(AetrException) { _status ->
    UniffiLib.INSTANCE.uniffi_aetr_core_fn_constructor_aetrsession_new(
        FfiConverterTypeSessionConfig.lower(`config`),_status)
}
    )

    protected val pointer: Pointer?
    protected val cleanable: UniffiCleaner.Cleanable

    private val wasDestroyed = AtomicBoolean(false)
    private val callCounter = AtomicLong(1)

    override fun destroy() {
        // Only allow a single call to this method.
        // TODO: maybe we should log a warning if called more than once?
        if (this.wasDestroyed.compareAndSet(false, true)) {
            // This decrement always matches the initial count of 1 given at creation time.
            if (this.callCounter.decrementAndGet() == 0L) {
                cleanable.clean()
            }
        }
    }

    @Synchronized
    override fun close() {
        this.destroy()
    }

    internal inline fun <R> callWithPointer(block: (ptr: Pointer) -> R): R {
        // Check and increment the call counter, to keep the object alive.
        // This needs a compare-and-set retry loop in case of concurrent updates.
        do {
            val c = this.callCounter.get()
            if (c == 0L) {
                throw IllegalStateException("${this.javaClass.simpleName} object has already been destroyed")
            }
            if (c == Long.MAX_VALUE) {
                throw IllegalStateException("${this.javaClass.simpleName} call counter would overflow")
            }
        } while (! this.callCounter.compareAndSet(c, c + 1L))
        // Now we can safely do the method call without the pointer being freed concurrently.
        try {
            return block(this.uniffiClonePointer())
        } finally {
            // This decrement always matches the increment we performed above.
            if (this.callCounter.decrementAndGet() == 0L) {
                cleanable.clean()
            }
        }
    }

    // Use a static inner class instead of a closure so as not to accidentally
    // capture `this` as part of the cleanable's action.
    private class UniffiCleanAction(private val pointer: Pointer?) : Runnable {
        override fun run() {
            pointer?.let { ptr ->
                uniffiRustCall { status ->
                    UniffiLib.INSTANCE.uniffi_aetr_core_fn_free_aetrsession(ptr, status)
                }
            }
        }
    }

    fun uniffiClonePointer(): Pointer {
        return uniffiRustCall() { status ->
            UniffiLib.INSTANCE.uniffi_aetr_core_fn_clone_aetrsession(pointer!!, status)
        }
    }

    
    /**
     * Encodes a text message into one complete 48 kHz PCM transmission
     * (all bursts, gaps, lead-in/tail) and caches the RS parity pool for a
     * later ARQ round.
     */
    @Throws(AetrException::class)override fun `encodeText`(`text`: kotlin.String): List<kotlin.Float> {
            return FfiConverterSequenceFloat.lift(
    callWithPointer {
    uniffiRustCallWithError(AetrException) { _status ->
    UniffiLib.INSTANCE.uniffi_aetr_core_fn_method_aetrsession_encode_text(
        it, FfiConverterString.lower(`text`),_status)
}
    }
    )
    }
    

    
    /**
     * Encodes a 48 kHz mono voice clip into one complete PCM transmission.
     * Rejects clips longer than the configured cap; caches the spans for a
     * later exact-retransmission ARQ round.
     */
    @Throws(AetrException::class)override fun `encodeVoice`(`pcm48k`: List<kotlin.Float>): List<kotlin.Float> {
            return FfiConverterSequenceFloat.lift(
    callWithPointer {
    uniffiRustCallWithError(AetrException) { _status ->
    UniffiLib.INSTANCE.uniffi_aetr_core_fn_method_aetrsession_encode_voice(
        it, FfiConverterSequenceFloat.lower(`pcm48k`),_status)
}
    }
    )
    }
    

    
    /**
     * Drains queued events. Also sweeps the reassembly timeout: stale
     * voice finalizes with silence gaps, stale text becomes `Failed`.
     * Poll at ~10 Hz from the UI.
     */override fun `pollEvents`(): List<RxEvent> {
            return FfiConverterSequenceTypeRxEvent.lift(
    callWithPointer {
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_aetr_core_fn_method_aetrsession_poll_events(
        it, _status)
}
    }
    )
    }
    

    
    /**
     * Feeds received PCM (any block size, called from the audio thread).
     * Cheap: buffers into the modem, decrypts any completed frames, and
     * queues events — including automatic `RepairRequested` responses when
     * a peer's control frame targets one of our cached messages. Frames
     * that fail authentication (wrong passphrase on the channel) or are
     * malformed are silently dropped, as on any shared radio channel.
     */override fun `pushRx`(`pcm48k`: List<kotlin.Float>)
        = 
    callWithPointer {
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_aetr_core_fn_method_aetrsession_push_rx(
        it, FfiConverterSequenceFloat.lower(`pcm48k`),_status)
}
    }
    
    

    
    /**
     * Builds the receiver side of the ARQ round: a single control-frame
     * transmission asking the original sender to repair `message_id`.
     * Errors if the message is unknown or already complete. The sender's
     * session answers automatically via `RxEvent::RepairRequested`.
     */
    @Throws(AetrException::class)override fun `requestRepair`(`messageId`: kotlin.ULong): List<kotlin.Float> {
            return FfiConverterSequenceFloat.lift(
    callWithPointer {
    uniffiRustCallWithError(AetrException) { _status ->
    UniffiLib.INSTANCE.uniffi_aetr_core_fn_method_aetrsession_request_repair(
        it, FfiConverterULong.lower(`messageId`),_status)
}
    }
    )
    }
    

    
    /**
     * Discards all receive state (in-flight messages, queued events,
     * modem sync). Keeps the key, mode, and sender-side ARQ caches.
     */override fun `resetRx`()
        = 
    callWithPointer {
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_aetr_core_fn_method_aetrsession_reset_rx(
        it, _status)
}
    }
    
    

    
    /**
     * Current receiver state for a UI badge.
     */override fun `rxState`(): RxState {
            return FfiConverterTypeRxState.lift(
    callWithPointer {
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_aetr_core_fn_method_aetrsession_rx_state(
        it, _status)
}
    }
    )
    }
    

    
    /**
     * The configured TX key-up delay in milliseconds.
     */override fun `txDelayMs`(): kotlin.UInt {
            return FfiConverterUInt.lift(
    callWithPointer {
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_aetr_core_fn_method_aetrsession_tx_delay_ms(
        it, _status)
}
    }
    )
    }
    

    
    /**
     * The configured voice clip cap in seconds.
     */override fun `voiceCapSecs`(): kotlin.UInt {
            return FfiConverterUInt.lift(
    callWithPointer {
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_aetr_core_fn_method_aetrsession_voice_cap_secs(
        it, _status)
}
    }
    )
    }
    

    

    
    
    companion object
    
}

/**
 * @suppress
 */
public object FfiConverterTypeAetrSession: FfiConverter<AetrSession, Pointer> {

    override fun lower(value: AetrSession): Pointer {
        return value.uniffiClonePointer()
    }

    override fun lift(value: Pointer): AetrSession {
        return AetrSession(value)
    }

    override fun read(buf: ByteBuffer): AetrSession {
        // The Rust code always writes pointers as 8 bytes, and will
        // fail to compile if they don't fit.
        return lift(Pointer(buf.getLong()))
    }

    override fun allocationSize(value: AetrSession) = 8UL

    override fun write(value: AetrSession, buf: ByteBuffer) {
        // The Rust code always expects pointers written as 8 bytes,
        // and will fail to compile if they don't fit.
        buf.putLong(Pointer.nativeValue(lower(value)))
    }
}



/**
 * Session parameters. The passphrase is the only shared secret; the mode
 * must match on both ends of the channel.
 */
data class SessionConfig (
    /**
     * Shared passphrase; fed through Argon2id to derive the session key.
     */
    var `passphrase`: kotlin.String, 
    /**
     * Modem payload mode (85/128/170 bytes per burst).
     */
    var `mode`: ModemMode, 
    /**
     * Maximum voice clip length accepted by `encode_voice`, in seconds.
     */
    var `voiceCapSecs`: kotlin.UInt = 30u, 
    /**
     * Extra wait before the first burst, in milliseconds, giving the radio
     * time to finish keying up (Bluetooth/VOX radios can take ~1 s). Added
     * on top of the fixed 0.1 s lead-in.
     */
    var `txDelayMs`: kotlin.UInt = 1000u, 
    /**
     * Fill the TX delay with a quiet primer tone instead of silence, so
     * radios that key on audio energy (VOX) open the transmitter during
     * the delay rather than clipping the start of the data.
     */
    var `voxPrimer`: kotlin.Boolean = false
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeSessionConfig: FfiConverterRustBuffer<SessionConfig> {
    override fun read(buf: ByteBuffer): SessionConfig {
        return SessionConfig(
            FfiConverterString.read(buf),
            FfiConverterTypeModemMode.read(buf),
            FfiConverterUInt.read(buf),
            FfiConverterUInt.read(buf),
            FfiConverterBoolean.read(buf),
        )
    }

    override fun allocationSize(value: SessionConfig) = (
            FfiConverterString.allocationSize(value.`passphrase`) +
            FfiConverterTypeModemMode.allocationSize(value.`mode`) +
            FfiConverterUInt.allocationSize(value.`voiceCapSecs`) +
            FfiConverterUInt.allocationSize(value.`txDelayMs`) +
            FfiConverterBoolean.allocationSize(value.`voxPrimer`)
    )

    override fun write(value: SessionConfig, buf: ByteBuffer) {
            FfiConverterString.write(value.`passphrase`, buf)
            FfiConverterTypeModemMode.write(value.`mode`, buf)
            FfiConverterUInt.write(value.`voiceCapSecs`, buf)
            FfiConverterUInt.write(value.`txDelayMs`, buf)
            FfiConverterBoolean.write(value.`voxPrimer`, buf)
    }
}





/**
 * Errors surfaced by the aetr core. Library paths never panic; every
 * fallible operation returns one of these. Crosses the FFI as a flat
 * error: bindings see the variant name plus the Display message.
 */
sealed class AetrException(message: String): kotlin.Exception(message) {
        
    /**
     * Key derivation failed (bad Argon2 parameters or output length).
     */
        class Kdf(message: String) : AetrException(message)
        
    /**
     * AEAD authentication failed: wrong passphrase or corrupted chunk.
     */
        class AuthFailed(message: String) : AetrException(message)
        
    /**
     * A frame or payload had an impossible size or malformed header.
     */
        class Malformed(message: String) : AetrException(message)
        
    /**
     * Reed-Solomon coding failed (shard count/size mismatch).
     */
        class Fec(message: String) : AetrException(message)
        
    /**
     * The voice codec or resampler rejected the input.
     */
        class Voice(message: String) : AetrException(message)
        
    /**
     * The C++ modem shim reported an error.
     */
        class Modem(message: String) : AetrException(message)
        
    /**
     * Message too large for the protocol limits (chunk_index is one byte).
     */
        class TooLarge(message: String) : AetrException(message)
        

    companion object ErrorHandler : UniffiRustCallStatusErrorHandler<AetrException> {
        override fun lift(error_buf: RustBuffer.ByValue): AetrException = FfiConverterTypeAetrError.lift(error_buf)
    }
}

/**
 * @suppress
 */
public object FfiConverterTypeAetrError : FfiConverterRustBuffer<AetrException> {
    override fun read(buf: ByteBuffer): AetrException {
        
            return when(buf.getInt()) {
            1 -> AetrException.Kdf(FfiConverterString.read(buf))
            2 -> AetrException.AuthFailed(FfiConverterString.read(buf))
            3 -> AetrException.Malformed(FfiConverterString.read(buf))
            4 -> AetrException.Fec(FfiConverterString.read(buf))
            5 -> AetrException.Voice(FfiConverterString.read(buf))
            6 -> AetrException.Modem(FfiConverterString.read(buf))
            7 -> AetrException.TooLarge(FfiConverterString.read(buf))
            else -> throw RuntimeException("invalid error enum value, something is very wrong!!")
        }
        
    }

    override fun allocationSize(value: AetrException): ULong {
        return 4UL
    }

    override fun write(value: AetrException, buf: ByteBuffer) {
        when(value) {
            is AetrException.Kdf -> {
                buf.putInt(1)
                Unit
            }
            is AetrException.AuthFailed -> {
                buf.putInt(2)
                Unit
            }
            is AetrException.Malformed -> {
                buf.putInt(3)
                Unit
            }
            is AetrException.Fec -> {
                buf.putInt(4)
                Unit
            }
            is AetrException.Voice -> {
                buf.putInt(5)
                Unit
            }
            is AetrException.Modem -> {
                buf.putInt(6)
                Unit
            }
            is AetrException.TooLarge -> {
                buf.putInt(7)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }

}



/**
 * Modem payload size selector. One frame = one burst = one transmission.
 */

enum class ModemMode {
    
    /**
     * 85-byte frames (most robust polar code).
     */
    B85,
    /**
     * 128-byte frames.
     */
    B128,
    /**
     * 170-byte frames (default).
     */
    B170;
    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypeModemMode: FfiConverterRustBuffer<ModemMode> {
    override fun read(buf: ByteBuffer) = try {
        ModemMode.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: ModemMode) = 4UL

    override fun write(value: ModemMode, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}





/**
 * What a payload is, for airtime estimation.
 */

enum class PayloadKind {
    
    /**
     * `len` is the UTF-8 byte count of the text.
     */
    TEXT,
    /**
     * `len` is the clip length in 48 kHz samples.
     */
    VOICE;
    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypePayloadKind: FfiConverterRustBuffer<PayloadKind> {
    override fun read(buf: ByteBuffer) = try {
        PayloadKind.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: PayloadKind) = 4UL

    override fun write(value: PayloadKind, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}





/**
 * Events drained by the UI via `poll_events`.
 */
sealed class RxEvent {
    
    /**
     * A complete text message.
     */
    data class Text(
        /**
         * Message id it arrived under.
         */
        val `messageId`: kotlin.ULong, 
        /**
         * Decoded UTF-8 text.
         */
        val `text`: kotlin.String) : RxEvent() {
        companion object
    }
    
    /**
     * A voice clip, possibly with silent gaps where spans were lost.
     */
    data class Voice(
        /**
         * Message id it arrived under.
         */
        val `messageId`: kotlin.ULong, 
        /**
         * 48 kHz mono PCM ready to play.
         */
        val `pcm48k`: List<kotlin.Float>, 
        /**
         * Span indices that were missing and filled with silence.
         */
        val `missingSpans`: List<kotlin.UInt>) : RxEvent() {
        companion object
    }
    
    /**
     * Reassembly progress for an in-flight message (emitted on change).
     */
    data class Progress(
        /**
         * Message being assembled.
         */
        val `messageId`: kotlin.ULong, 
        /**
         * Distinct shards held so far.
         */
        val `received`: kotlin.UInt, 
        /**
         * Shards needed to complete (K for text, span count for voice).
         */
        val `total`: kotlin.UInt, 
        /**
         * Whether the message is voice.
         */
        val `isVoice`: kotlin.Boolean) : RxEvent() {
        companion object
    }
    
    /**
     * A receiver asked us to repair a message we sent. `pcm_response` is
     * the ready-to-transmit repair burst; the app decides when to key up.
     */
    data class RepairRequested(
        /**
         * Our message the peer wants repaired.
         */
        val `messageId`: kotlin.ULong, 
        /**
         * Complete 48 kHz PCM answering the request.
         */
        val `pcmResponse`: List<kotlin.Float>) : RxEvent() {
        companion object
    }
    
    /**
     * A message that timed out or an internal receive-path error
     * (message_id 0 when no message is attributable).
     */
    data class Failed(
        /**
         * Message id of the failed message, or 0.
         */
        val `messageId`: kotlin.ULong, 
        /**
         * Why it failed.
         */
        val `reason`: kotlin.String) : RxEvent() {
        companion object
    }
    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeRxEvent : FfiConverterRustBuffer<RxEvent>{
    override fun read(buf: ByteBuffer): RxEvent {
        return when(buf.getInt()) {
            1 -> RxEvent.Text(
                FfiConverterULong.read(buf),
                FfiConverterString.read(buf),
                )
            2 -> RxEvent.Voice(
                FfiConverterULong.read(buf),
                FfiConverterSequenceFloat.read(buf),
                FfiConverterSequenceUInt.read(buf),
                )
            3 -> RxEvent.Progress(
                FfiConverterULong.read(buf),
                FfiConverterUInt.read(buf),
                FfiConverterUInt.read(buf),
                FfiConverterBoolean.read(buf),
                )
            4 -> RxEvent.RepairRequested(
                FfiConverterULong.read(buf),
                FfiConverterSequenceFloat.read(buf),
                )
            5 -> RxEvent.Failed(
                FfiConverterULong.read(buf),
                FfiConverterString.read(buf),
                )
            else -> throw RuntimeException("invalid enum value, something is very wrong!!")
        }
    }

    override fun allocationSize(value: RxEvent) = when(value) {
        is RxEvent.Text -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4UL
                + FfiConverterULong.allocationSize(value.`messageId`)
                + FfiConverterString.allocationSize(value.`text`)
            )
        }
        is RxEvent.Voice -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4UL
                + FfiConverterULong.allocationSize(value.`messageId`)
                + FfiConverterSequenceFloat.allocationSize(value.`pcm48k`)
                + FfiConverterSequenceUInt.allocationSize(value.`missingSpans`)
            )
        }
        is RxEvent.Progress -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4UL
                + FfiConverterULong.allocationSize(value.`messageId`)
                + FfiConverterUInt.allocationSize(value.`received`)
                + FfiConverterUInt.allocationSize(value.`total`)
                + FfiConverterBoolean.allocationSize(value.`isVoice`)
            )
        }
        is RxEvent.RepairRequested -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4UL
                + FfiConverterULong.allocationSize(value.`messageId`)
                + FfiConverterSequenceFloat.allocationSize(value.`pcmResponse`)
            )
        }
        is RxEvent.Failed -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                4UL
                + FfiConverterULong.allocationSize(value.`messageId`)
                + FfiConverterString.allocationSize(value.`reason`)
            )
        }
    }

    override fun write(value: RxEvent, buf: ByteBuffer) {
        when(value) {
            is RxEvent.Text -> {
                buf.putInt(1)
                FfiConverterULong.write(value.`messageId`, buf)
                FfiConverterString.write(value.`text`, buf)
                Unit
            }
            is RxEvent.Voice -> {
                buf.putInt(2)
                FfiConverterULong.write(value.`messageId`, buf)
                FfiConverterSequenceFloat.write(value.`pcm48k`, buf)
                FfiConverterSequenceUInt.write(value.`missingSpans`, buf)
                Unit
            }
            is RxEvent.Progress -> {
                buf.putInt(3)
                FfiConverterULong.write(value.`messageId`, buf)
                FfiConverterUInt.write(value.`received`, buf)
                FfiConverterUInt.write(value.`total`, buf)
                FfiConverterBoolean.write(value.`isVoice`, buf)
                Unit
            }
            is RxEvent.RepairRequested -> {
                buf.putInt(4)
                FfiConverterULong.write(value.`messageId`, buf)
                FfiConverterSequenceFloat.write(value.`pcmResponse`, buf)
                Unit
            }
            is RxEvent.Failed -> {
                buf.putInt(5)
                FfiConverterULong.write(value.`messageId`, buf)
                FfiConverterString.write(value.`reason`, buf)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }
}





/**
 * Receiver state for UI badges.
 */

enum class RxState {
    
    /**
     * No signal being tracked.
     */
    IDLE,
    /**
     * A burst preamble was detected; payload symbols are being collected.
     */
    SYNCING,
    /**
     * At least one message is partially reassembled.
     */
    RECEIVING;
    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypeRxState: FfiConverterRustBuffer<RxState> {
    override fun read(buf: ByteBuffer) = try {
        RxState.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: RxState) = 4UL

    override fun write(value: RxState, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}






/**
 * @suppress
 */
public object FfiConverterSequenceUInt: FfiConverterRustBuffer<List<kotlin.UInt>> {
    override fun read(buf: ByteBuffer): List<kotlin.UInt> {
        val len = buf.getInt()
        return List<kotlin.UInt>(len) {
            FfiConverterUInt.read(buf)
        }
    }

    override fun allocationSize(value: List<kotlin.UInt>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterUInt.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<kotlin.UInt>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterUInt.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceFloat: FfiConverterRustBuffer<List<kotlin.Float>> {
    override fun read(buf: ByteBuffer): List<kotlin.Float> {
        val len = buf.getInt()
        return List<kotlin.Float>(len) {
            FfiConverterFloat.read(buf)
        }
    }

    override fun allocationSize(value: List<kotlin.Float>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterFloat.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<kotlin.Float>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterFloat.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeRxEvent: FfiConverterRustBuffer<List<RxEvent>> {
    override fun read(buf: ByteBuffer): List<RxEvent> {
        val len = buf.getInt()
        return List<RxEvent>(len) {
            FfiConverterTypeRxEvent.read(buf)
        }
    }

    override fun allocationSize(value: List<RxEvent>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeRxEvent.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<RxEvent>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeRxEvent.write(it, buf)
        }
    }
}
        /**
         * Estimates on-air seconds for a payload in a given mode, including the
         * TX key-up delay, lead-in, inter-burst gaps, and tail. For `Text`, `len`
         * is UTF-8 bytes; for `Voice`, `len` is 48 kHz samples. The UIs use this
         * to show the cost of longer voice caps, robust modes, and TX delay
         * before transmitting.
         */ fun `estimateAirtimeSecs`(`mode`: ModemMode, `kind`: PayloadKind, `len`: kotlin.ULong, `txDelayMs`: kotlin.UInt): kotlin.Double {
            return FfiConverterDouble.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_aetr_core_fn_func_estimate_airtime_secs(
        FfiConverterTypeModemMode.lower(`mode`),FfiConverterTypePayloadKind.lower(`kind`),FfiConverterULong.lower(`len`),FfiConverterUInt.lower(`txDelayMs`),_status)
}
    )
    }
    


